version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: shelterlink-db
    environment:
      POSTGRES_DB: shelterlink
      POSTGRES_USER: shelterlink
      POSTGRES_PASSWORD: shelterlink_dev
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./apps/api/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shelterlink -d shelterlink"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
